Algoritmo "Meu Primeiro Algoritmo"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Rafael de Almeida Araújo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/04/2022
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva("Resultado:", nota)

Fimalgoritmo